"""
UBX RXM-SFRBX Navigation Data Subframe Definitions

Created on 31 Oct 2021

GPS information sourced from https://www.gps.gov/technical/icwg/IS-GPS-200L.pdf

*** NB: THESE PAYLOADS ARE BIG ENDIAN - MSB TRANSMITTED FIRST ***

:author: semuadmin
"""

from pyubx2.ubxtypes_core import (
    U1,
    U2,
    U3,
    U4,
    U5,
    U6,
    U8,
    U22,
)

U10 = "U010"  # Unsigned Int 10 bytes
U16 = "U016"  # Unsigned Int 16 bytes
U17 = "U017"  # Unsigned Int 17 bytes
U23 = "U023"  # Unsigned Int 23 bytes
U24 = "U024"  # Unsigned Int 24 bytes

GPS_SUBFRAMES = {
    GPS_SFR_1: {
        "word1_tlm": U22,
        "word1_isf": U1,
        "word1_reserved1": U1,
        "word1_parity": U6,
        "word2_tow": U17,
        "word2_alert": U1,
        "word2_antispoof": U1,
        "word2_sfrid": U3,  # 0x001, 0x010, 0x011, 0x100, 0x101
        "word2_paritycomp": U2,
        "word2_parity": U6,
        "word3_week": U10,
        "word3_l2code": U2,
        "word3_uraIndex": U4,
        "word3_svHealth1": U1,
        "word3_svHealth2": U5,
        "word3_iodc_msb": U2,
        "word3_parity": U6,
        "word4_l2p": U1,
        "word4": U23,
        "word4_parity": U6,
        "word5": U24,
        "word5_parity": U4,
        "word6": U24,
        "word6_parity": U6,
        "word7": U16,
        "word7_tgd": U8,
        "word7_parity": U6,
        "word8_iodc_lsb": U8,
        "word8_toc": U16,
        "word8_parity": U6,
        "word9_af2": U8,
        "word9_af1": U16,
        "word9_parity": U6,
        "word10_af0": U22,
        "word10_paritycomp": U2,
        "word10_parity": U6,
    },
    GPS_SFR_2: {
        "word1_tlm": U22,
        "word1_isf": U1,
        "word1_reserved1": U1,
        "word1_parity": U6,
        "word2_tow": U17,
        "word2_alert": U1,
        "word2_antispoof": U1,
        "word2_sfrid": U3,
        "word2_paritycomp": U2,
        "word2_parity": U6,
        "word3": U24,
        "word3_parity": U6,
        "word4": U24,
        "word4_parity": U6,
        "word5": U24,
        "word5_parity": U6,
        "word6": U24,
        "word6_parity": U6,
        "word7": U24,
        "word7_parity": U6,
        "word8": U24,
        "word8_parity": U6,
        "word9": U24,
        "word9_parity": U6,
        "word10": U24,
        "word10_parity": U6,
    },
    GPS_SFR_3: {
        "word1_tlm": U22,
        "word1_isf": U1,
        "word1_reserved1": U1,
        "word1_parity": U6,
        "word2_tow": U17,
        "word2_alert": U1,
        "word2_antispoof": U1,
        "word2_sfrid": U3,
        "word2_paritycomp": U2,
        "word2_parity": U6,
        "word3": U24,
        "word3_parity": U6,
        "word4": U24,
        "word4_parity": U6,
        "word5": U24,
        "word5_parity": U6,
        "word6": U24,
        "word6_parity": U6,
        "word7": U24,
        "word7_parity": U6,
        "word8": U24,
        "word8_parity": U6,
        "word9": U24,
        "word9_parity": U6,
        "word10": U24,
        "word10_parity": U6,
    },
    GPS_SFR_4: {
        "word1_tlm": U22,
        "word1_isf": U1,
        "word1_reserved1": U1,
        "word1_parity": U6,
        "word2_tow": U17,
        "word2_alert": U1,
        "word2_antispoof": U1,
        "word2_sfrid": U3,
        "word2_paritycomp": U2,
        "word2_parity": U6,
        "word3": U24,
        "word3_parity": U6,
        "word4": U24,
        "word4_parity": U6,
        "word5": U24,
        "word5_parity": U6,
        "word6": U24,
        "word6_parity": U6,
        "word7": U24,
        "word7_parity": U6,
        "word8": U24,
        "word8_parity": U6,
        "word9": U24,
        "word9_parity": U6,
        "word10": U24,
        "word10_parity": U6,
    },
    GPS_SFR_5: {
        "word1_tlm": U22,
        "word1_isf": U1,
        "word1_reserved1": U1,
        "word1_parity": U6,
        "word2_tow": U17,
        "word2_alert": U1,
        "word2_antispoof": U1,
        "word2_sfrid": U3,
        "word2_paritycomp": U2,
        "word2_parity": U6,
        "word3": U24,
        "word3_parity": U6,
        "word4": U24,
        "word4_parity": U6,
        "word5": U24,
        "word5_parity": U6,
        "word6": U24,
        "word6_parity": U6,
        "word7": U24,
        "word7_parity": U6,
        "word8": U24,
        "word8_parity": U6,
        "word9": U24,
        "word9_parity": U6,
        "word10": U24,
        "word10_parity": U6,
    },
}

GLONASS_SUBFRAMES = {}

GALILEO_SUBFRAMES = {}

BEIDOU_SUBFRAMES = {}
